# CodeRabbit AI Review Policy — Project Chimera
# Instructs reviewer to check Spec Alignment and Security. Task 3.3

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  poem: false

  path_filters:
    - "!*.md"
    - "!*.pdf"
    - "specs/**"
    - "skills/**"
    - "tests/**"
    - "*.py"
    - "Dockerfile"
    - "Makefile"
    - "pyproject.toml"

  path_instructions:
    - path: "specs/*"
      instructions: |
        Check alignment with SRS and 3-Day Challenge requirements.
        Verify _meta, functional, technical, openclaw specs are consistent.
    - path: "skills/*"
      instructions: |
        Verify skills match IO contracts in specs/technical.md and skills/README.md.
        No direct API calls; all external I/O via MCP.
    - path: "tests/*"
      instructions: |
        Tests must define contracts (TDD). Check they assert correct structures.
    - path: "**/*.py"
      instructions: |
        Check for: spec alignment, no hardcoded secrets, MCP-first pattern.
        Flag security issues (log injection, path traversal, etc.).
